add wave -noupdate -format Logic /testbnch/clk
add wave -noupdate -format Logic /testbnch/reset_n
add wave -noupdate -format Literal /testbnch/cpucontrol
add wave -noupdate -format Literal /testbnch/uartstatus1
add wave -noupdate -format Literal /testbnch/uartstatus2
add wave -noupdate -format Literal /testbnch/uartconfig1
add wave -noupdate -format Literal /testbnch/uartconfig2
add wave -noupdate -format Literal /testbnch/cpudata
add wave -noupdate -format Logic /testbnch/txdata1
add wave -noupdate -format Logic /testbnch/rxdata1
add wave -noupdate -format Logic /testbnch/txdata2
add wave -noupdate -format Logic /testbnch/rxdata2
